#!/usr/bin/env bash
# Gamebridge Installer
# Reads a YAML config file and automates the gamebridge setup.
# See gamebridge.conf.example.yaml for configuration reference.
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

DRY_RUN=false
CONFIG_FILE=""
CONFIG_JSON=""

usage() {
    cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Gamebridge Installer - LAN Game Server Rebroadcaster over VLANs

Options:
  -c, --config FILE    Path to YAML configuration file (.yaml or .yml)
  -d, --dry-run        Show what would be done without making changes
  -s, --status         Show current bridge/ebtables status and exit
  -h, --help           Show this help message

Examples:
  sudo $SCRIPT_NAME -c gamebridge.conf.yaml
  $SCRIPT_NAME -c gamebridge.conf.yaml --dry-run
  sudo $SCRIPT_NAME --status
EOF
}

log()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()  { err "$@"; exit 1; }

# ---------------------------------------------------------------------------
# Config parsing (uses Python 3 — available by default on Debian 12)
# ---------------------------------------------------------------------------

parse_config() {
    python3 - "$1" << 'PYEOF'
import sys, json, os

config_file = sys.argv[1]
ext = os.path.splitext(config_file)[1].lower()

if ext not in ('.yaml', '.yml'):
    print(f"ERROR: Config file must be YAML (.yaml or .yml), got '{ext}'", file=sys.stderr)
    sys.exit(1)

try:
    import yaml
except ImportError:
    print("ERROR: python3-yaml is required. Install with: apt-get install python3-yaml", file=sys.stderr)
    sys.exit(1)

with open(config_file) as f:
    data = yaml.safe_load(f)

# --- validate required fields ---
errors = []
for key in ('management', 'trunk_interface', 'vlans', 'game_ports'):
    if key not in data:
        errors.append(f"Missing required key: {key}")
if 'management' in data:
    for sub in ('interface', 'address', 'netmask', 'gateway'):
        if sub not in data['management']:
            errors.append(f"Missing required key: management.{sub}")
if 'vlans' in data and not isinstance(data['vlans'], list):
    errors.append("'vlans' must be a list")
if 'game_ports' in data and not isinstance(data['game_ports'], list):
    errors.append("'game_ports' must be a list")

if errors:
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    sys.exit(1)

# Apply defaults
data.setdefault('bridge', 'br0')

json.dump(data, sys.stdout)
PYEOF
}

# Retrieve a dotted key from CONFIG_JSON.  Lists are printed one element per line.
config_get() {
    echo "$CONFIG_JSON" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for k in sys.argv[1].split('.'):
    data = data[int(k)] if isinstance(data, list) else data[k]
if isinstance(data, list):
    for item in data:
        print(item)
else:
    print(data)
" "$1"
}

# ---------------------------------------------------------------------------
# Installation steps
# ---------------------------------------------------------------------------

install_packages() {
    log "Installing required packages (bridge-utils, ebtables)..."
    if $DRY_RUN; then
        echo "  [DRY RUN] apt-get update -qq"
        echo "  [DRY RUN] apt-get install -y bridge-utils ebtables"
    else
        apt-get update -qq
        apt-get install -y bridge-utils ebtables
    fi
}

enable_8021q() {
    log "Enabling 802.1Q VLAN tagging module..."
    if grep -q '^8021q$' /etc/modules 2>/dev/null; then
        log "802.1Q already present in /etc/modules — skipping"
    else
        if $DRY_RUN; then
            echo "  [DRY RUN] echo 8021q >> /etc/modules"
        else
            echo 8021q >> /etc/modules
        fi
    fi
}

generate_interfaces() {
    log "Generating /etc/network/interfaces..."

    local mgmt_iface mgmt_addr mgmt_netmask mgmt_gateway trunk_iface bridge
    mgmt_iface=$(config_get management.interface)
    mgmt_addr=$(config_get management.address)
    mgmt_netmask=$(config_get management.netmask)
    mgmt_gateway=$(config_get management.gateway)
    trunk_iface=$(config_get trunk_interface)
    bridge=$(config_get bridge)

    local tmp_file
    tmp_file=$(mktemp)

    # Header + loopback + management interface
    cat > "$tmp_file" << EOF
# /etc/network/interfaces
# Generated by gamebridge installer on $(date -Iseconds)

auto lo
iface lo inet loopback

auto ${mgmt_iface}
iface ${mgmt_iface} inet static
        address ${mgmt_addr}
        netmask ${mgmt_netmask}
        gateway ${mgmt_gateway}

EOF

    # VLAN sub-interfaces
    local bridge_ports=""
    while IFS= read -r vlan; do
        cat >> "$tmp_file" << EOF
auto ${trunk_iface}.${vlan}
iface ${trunk_iface}.${vlan} inet manual

EOF
        bridge_ports="${bridge_ports:+${bridge_ports} }${trunk_iface}.${vlan}"
    done < <(config_get vlans)

    # Bridge (not auto — brought up manually after ebtables rules are applied)
    cat >> "$tmp_file" << EOF
# ${bridge} is brought up manually by rc.local after ebtables filtering is in place
iface ${bridge} inet manual
        bridge_ports ${bridge_ports}
EOF

    if $DRY_RUN; then
        log "Would write /etc/network/interfaces:"
        echo "--- begin ---"
        cat "$tmp_file"
        echo "--- end ---"
    else
        if [ -f /etc/network/interfaces ]; then
            cp /etc/network/interfaces "/etc/network/interfaces.bak.$(date +%Y%m%d%H%M%S)"
            log "Backed up existing /etc/network/interfaces"
        fi
        cp "$tmp_file" /etc/network/interfaces
        log "Wrote /etc/network/interfaces"
    fi
    rm -f "$tmp_file"
}

generate_rclocal() {
    log "Generating /etc/rc.local..."

    local bridge
    bridge=$(config_get bridge)

    local tmp_file
    tmp_file=$(mktemp)

    cat > "$tmp_file" << 'EOF'
#!/bin/sh -e
# /etc/rc.local
# Generated by gamebridge installer
# Sets up ebtables filtering and brings up the bridge.

# Drop all forwarded traffic by default
ebtables -P FORWARD DROP
ebtables -F FORWARD

# Allow game server discovery broadcasts (UDP)
EOF

    # Append one ebtables rule per port range
    while IFS= read -r port_range; do
        echo "ebtables -A FORWARD -d Broadcast -p IPv4 --ip-protocol udp --ip-destination-port ${port_range} -j ACCEPT" >> "$tmp_file"
    done < <(config_get game_ports)

    # Bring up bridge and SNAT
    cat >> "$tmp_file" << EOF

# Bring up bridge interface
ifup ${bridge}

# SNAT source MAC address of forwarded frames to the bridge MAC
BRIDGE_MAC=\$(cat /sys/class/net/${bridge}/address)
ebtables -t nat -A POSTROUTING -j snat --to-src \$BRIDGE_MAC --snat-target ACCEPT

exit 0
EOF

    if $DRY_RUN; then
        log "Would write /etc/rc.local:"
        echo "--- begin ---"
        cat "$tmp_file"
        echo "--- end ---"
    else
        if [ -f /etc/rc.local ]; then
            cp /etc/rc.local "/etc/rc.local.bak.$(date +%Y%m%d%H%M%S)"
            log "Backed up existing /etc/rc.local"
        fi
        cp "$tmp_file" /etc/rc.local
        chmod +x /etc/rc.local
        log "Wrote /etc/rc.local"
    fi
    rm -f "$tmp_file"
}

enable_rclocal() {
    log "Enabling rc-local service..."
    if $DRY_RUN; then
        echo "  [DRY RUN] systemctl daemon-reload"
        echo "  [DRY RUN] systemctl enable rc-local"
    else
        systemctl daemon-reload
        systemctl enable rc-local
    fi
}

show_status() {
    log "Network links:"
    ip link
    echo ""
    log "Bridge status:"
    brctl show
    echo ""
    log "ebtables FORWARD rules:"
    ebtables -L FORWARD --Lc --Ln
    echo ""
    log "ebtables nat POSTROUTING rules:"
    ebtables -t nat -L POSTROUTING --Lc --Ln
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    local show_status_only=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -c|--config)  CONFIG_FILE="$2"; shift 2 ;;
            -d|--dry-run) DRY_RUN=true; shift ;;
            -s|--status)  show_status_only=true; shift ;;
            -h|--help)    usage; exit 0 ;;
            *)            die "Unknown option: $1\nRun '$SCRIPT_NAME --help' for usage." ;;
        esac
    done

    if $show_status_only; then
        show_status
        exit 0
    fi

    if [[ -z "$CONFIG_FILE" ]]; then
        die "Config file is required. Use -c/--config to specify.\nRun '$SCRIPT_NAME --help' for usage."
    fi

    if [[ ! -f "$CONFIG_FILE" ]]; then
        die "Config file not found: $CONFIG_FILE"
    fi

    if ! command -v python3 &>/dev/null; then
        die "python3 is required but not found"
    fi

    if [[ "$(id -u)" -ne 0 ]] && ! $DRY_RUN; then
        die "This script must be run as root (use sudo) or pass --dry-run to preview."
    fi

    log "Parsing configuration from ${CONFIG_FILE}..."
    CONFIG_JSON=$(parse_config "$CONFIG_FILE")
    if [[ -z "$CONFIG_JSON" ]]; then
        die "Failed to parse config file"
    fi

    if $DRY_RUN; then
        warn "DRY RUN MODE — no changes will be made"
        echo ""
    fi

    install_packages
    enable_8021q
    generate_interfaces
    generate_rclocal
    enable_rclocal

    echo ""
    if $DRY_RUN; then
        log "Dry run complete. Review the output above."
    else
        log "Installation complete!"
        log "Reboot the system to apply all changes:"
        log "  reboot"
        echo ""
        log "After reboot, verify with:"
        log "  sudo $SCRIPT_NAME --status"
    fi
}

main "$@"
